spring.application.name=backend
server.port=8081

spring.datasource.url=jdbc:sqlserver://GIGARBAGE\\SQLEXPRESS;databaseName=BKExpress;trustServerCertificate=true;encrypt=false
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=thaulemon
spring.datasource.password=Yang@0487

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
